spring:
  application:
    name: fursa-backend
  datasource:
    url: jdbc:postgresql://localhost:5432/fursa
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always
  security:
    enabled: false



blockchain:
  rpc-url: http://127.0.0.1:8545
  contract-address: "0x5b1869D9A4C187F2EAa108f3062412ecf0526b24"
  owner-private-key: "0x4f3edf983ac636a65a842ce7c78d9aa706d3b113bce9c46f30d7d21715b23b1d"
  gas-price: 2000000000
  gas-limit: 30000000